# Generated by Django 4.0.7 on 2022-09-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='espera_completo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
